import { Providers } from "./provider";

export const metadata = {
  title: "Leave Manager",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="icon"
          href="/icon?<generated>"
          type="image/<generated>"
          sizes="<generated>"
        />
      </head>
      <body style={{ backgroundColor: "lavender" }}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
